version: '3.1'

services:
  raven:
    image: artiefuzzz/raven    
    tty: true
    restart: always
    build: .
    container_name: raven
    env_file:
      - "src/.env.development"
      - "src/.env.development.local"
      - "prisma/.env.production.local"
    networks:
      - raven
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - raven
    volumes:
      - './postgres:/var/lib/postgresql/data'
  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - raven
  influx:
    image: influxdb:2.1-alpine
    command: 'influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store disk'
    container_name: influx
    restart: always
    ports:
      - 8086:8086
    networks:
      - raven
    volumes:
      - './influx-data:/var/lib/influxdb2'

networks:
  raven:
