version: '3.1'

services:

  bot:
    tty: true
    restart: always
    build: .
    container_name: raven
    env_file:
      - "src/.env.development"
      - "src/.env.development.local"
      - "prisma/.env.production.local"
    networks:
      - bot
    depends_on:
      - postgres
      - redis
  postgres:
    image: postgres:alpine
    restart: always
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - bot
    volumes:
      - './postgres:/var/lib/postgresql/data'
  redis:
    image: redis:alpine
    command: redis-server --requirepass redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    networks:
      - bot

networks:
  bot:
